name: "All jobs"

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *" # Every 5 minutes

env:
  PK_1: ${{ secrets.PK_1 }}
  PK_2: ${{ secrets.PK_2 }}
  PK_3: ${{ secrets.PK_3 }}
  TG_API_KEY_GOV_CHANNEL: ${{ secrets.TG_API_KEY_GOV_CHANNEL }}
  TG_API_KEY: ${{ secrets.TG_API_KEY }}
  PK_BOT_REPLICATION: ${{ secrets.PK_BOT_REPLICATION }}
  TG_API_KEY_BOT_ERROR: ${{ secrets.TG_API_KEY_BOT_ERROR }}
  FRAX_DELEGATION_MAINNET: ${{ secrets.FRAX_DELEGATION_MAINNET }}
  FRAX_DELEGATION_FRAXTAL: ${{ secrets.FRAX_DELEGATION_FRAXTAL }}
  WEB3_ALCHEMY_API_KEY: ${{ secrets.WEB3_ALCHEMY_API_KEY }}
  SAFE_PROPOSER_PK: ${{ secrets.SAFE_PROPOSER_PK }}
  TENDERLY_ACCESS_KEY: ${{ secrets.TENDERLY_ACCESS_KEY }}
  TENDERLY_ACCOUNT_SLUG: ${{ secrets.TENDERLY_ACCOUNT_SLUG }}
  TENDERLY_PROJECT_SLUG: ${{ secrets.TENDERLY_PROJECT_SLUG }}

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run mirror
      - run: npm run mirror-crv
      - run: npm run replication
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_user_name: GitHub Action Bot
          commit_user_email: action@github.com
          commit_author: GitHub Action Bot <action@github.com>
